### ISSUE TITLE
[Feat] 2주차 과제

### ISSUE THREAD

**Issue by yujin-00** [GO-SOPT-iOS-Part/NamYuJin#3]
## Description
- 2차 세미나 과제!
- 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 수정(비활성화일 때는 제일 기본)
- 아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼 활성화
- 활성화 된 로그인하기 버튼을 클릭했을 때, 아이디를 데이터 전달
- 비밀번호 텍스트필드 default 값은 security 적용
- 눈 모양 버튼을 클릭 시, security를 해제
- 글 삭제 버튼을 클릭 시, 아이디, 비밀번호 텍스트필드를 각각 클리어

## To-do
- [x] 텍스트필드 클릭했을 때 활성화
- [x] 아이디, 비밀번호 텍스트필드 찼을 때 버튼 활성화
- [x] 비밀번호 security 적용
- [x] 아이디, 비밀번호 눈/삭제 버튼 추가 및 기능 구현
