### ISSUE TITLE
[Feat] 3주차 과제

### ISSUE THREAD

**Issue by yujin-00** [GO-SOPT-iOS-Part/NamYuJin#5]
## Description
- 3차 세미나 과제
- CustomView, 테이블뷰, 컬렉션뷰
- 마이페이지 구현하기
- Welcome -> Main -> MyPage 플로우

## To-do
- [x] Main페이지 만들고 버튼 추가
- [x] MyPage 프로필, 라벨 추가
- [x] MyPage 테이블뷰
- [x] Welcome -> Main -> MyPage 연결
